-- Adds Alubri's five intimate-care products to the live catalog
-- (Vaginal Moisturizing Gel, Intimate Serum, Calming Cream, Vulva Balm,
-- Vaginal Wellness Kit). Catalog entries only — Alubri is NOT an ayna brand
-- partner. Extracted from a regenerated supabase/seed/product_catalog.sql
-- (`npm run catalog:export`); just the 5 new rows, safe to run standalone.
-- Idempotent: safe to re-run.

insert into public.product_catalog (id, name, brand, category, product_type, summary, price, image, url, tags, health_functions, where_to_buy, where_to_buy_in_stock, safety, doctor_opinion, community_review, effectiveness, clinician_opinion_source, clinician_attribution, source, internal, requires_prescription, user_rating, is_active, extra)
values
  ('p-alubri-vaginal-moisturizing-gel', 'Alubri Vaginal Moisturizing Gel', 'Alubri', 'intimate-care', 'physical', 'A hormone-free internal vaginal moisturizer gel for dryness and discomfort, with up to 72 hours of hydration from a single application per the brand. It pairs hyaluronic acid (sodium hyaluronate) and lactic acid with Alubri''s "Activated Oil Complex" (pre-activated coconut and rosehip oils), dragon fruit extract, and aloe, which the brand positions as also supporting a balanced vaginal microbiome. A 1-month supply: a 50 mL tube with 8 single-use applicators, used about twice a week.', '$29.99 (50 mL, 8 applicators)', '/products/alubri/vaginal-moisturizing-gel.webp', 'https://alubri.com/products/vaginal-moisturizing-gel', '["discomfort","comfort","menopause","hormone-free"]'::jsonb, '["vaginal-health"]'::jsonb, '["alubri.com","Amazon","Walmart","Target","Mayo Clinic Store"]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Sold as a cosmetic / personal-care vaginal moisturizer; not an FDA-cleared medical device or drug.","materials":"50 mL (1.7 fl oz) tube with 8 single-use applicators. Ingredients: aqua (water), glucomannan, hydrolyzed Rosa canina (rosehip) fruit oil, hydrolyzed Cocos nucifera (coconut) oil, sodium hyaluronate, lactic acid, Hylocereus undatus (dragon fruit) fruit extract, Aloe barbadensis leaf juice, propanediol, xanthan gum, potassium sorbate, sodium benzoate, benzyl alcohol, benzoic acid. Fragrance-free and hormone-free.","recalls":"No recalls found.","sideEffects":"Discontinue and see a doctor if you notice irritation, burning, or an allergic reaction. Full warnings are listed below.","opinionAlerts":"The clinical figures (72-hour hydration, microbiome effects) come from studies the brand cites on its own site; ayna couldn''t find them published as a peer-reviewed paper."}'::jsonb, 'Alubri says its products are co-developed by an OB/GYN: co-founder Dr. Nicole Kerner, a board-certified, menopause-certified OB-GYN with 20+ years of clinical experience, per the brand.,
  ('p-alubri-intimate-serum', 'Alubri Intimate Serum', 'Alubri', 'intimate-care', 'physical', 'A lightweight, water-based serum for daily hydration of external intimate skin — the vulva, clitoris, labia, and vaginal opening. It pairs hyaluronic acid (sodium hyaluronate) with inulin (a prebiotic humectant), aloe, green tea, and chamomile to soothe dryness and support the skin''s moisture barrier, and the brand says it also promotes natural moisturization and lubrication. Non-sticky, hormone-free, and fragrance-free.', '$24.99 (50 mL)', '/products/alubri/intimate-serum.webp', 'https://alubri.com/products/intimate-serum', '["discomfort","comfort","hormone-free","external-only"]'::jsonb, '["vaginal-health"]'::jsonb, '["alubri.com","Amazon","Walmart","Mayo Clinic Store"]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Sold as a cosmetic / personal-care product; not an FDA-cleared medical device or drug.","materials":"50 mL (1.7 fl oz) pump bottle. Ingredients: aqua (water), betaine, inulin, sodium lactate, lactic acid, sodium hyaluronate, Aloe barbadensis leaf juice, Camellia sinensis (green tea) leaf extract, Chamomilla recutita (chamomile) flower extract, tocopherol, ethylhexylglycerin, hydroxyethylcellulose, xanthan gum, disodium phosphate, sodium phosphate, citric acid, phenoxyethanol, potassium sorbate, sodium benzoate, sodium hydroxide. Fragrance-free, hormone-free, hypoallergenic.","recalls":"No recalls found.","sideEffects":"Discontinue and see a doctor if you notice irritation or an allergic reaction. Full warnings are listed below.","opinionAlerts":"Brand states products are \"not intended to diagnose, treat, cure, or prevent any disease.\" Clinical figures are brand-reported."}'::jsonb, 'Alubri says its products are co-developed by co-founder Dr. Nicole Kerner, a board-certified, menopause-certified OB-GYN, and that this serum is gynecologist- and dermatologist-tested.,
  ('p-alubri-calming-cream', 'Alubri Calming Cream', 'Alubri', 'intimate-care', 'physical', 'An over-the-counter anti-itch cream made for intimate skin: 0.25% hydrocortisone to temporarily relieve external feminine itching and irritation, in a skincare-style base with hyaluronic acid, lactic acid, oat, aloe, and Alubri''s Activated Oil Complex. The brand positions it as giving the instant relief of an OTC ointment with a lighter, non-greasy feel, while supporting a balanced vaginal microbiome.', '$29.99 (50 mL)', '/products/alubri/calming-cream.png', 'https://alubri.com/products/calming-cream', '["discomfort","comfort","external-only"]'::jsonb, '["vaginal-health"]'::jsonb, '["alubri.com","Amazon","Target"]'::jsonb, '{}'::jsonb, '{"fdaStatus":"An over-the-counter external analgesic drug (hydrocortisone 0.25%), sold with a Drug Facts label; not a prescription product.","materials":"50 mL (1.7 fl oz) tube. Active ingredient: hydrocortisone 0.25% (external analgesic). Inactive ingredients: aqua (water), propanediol, cetearyl alcohol, isopropyl palmitate, Butyrospermum parkii (shea) butter, caprylic/capric triglycerides, dimethicone, Cocos nucifera (coconut) oil, glyceryl stearate, hydrolyzed Rosa canina (rosehip) fruit oil, hydrolyzed Cocos nucifera (coconut) oil, sodium hyaluronate, lactic acid, Avena sativa (oat) meal extract, tocopherol, Aloe barbadensis.","recalls":"No recalls found.","sideEffects":"Hydrocortisone is a mild topical steroid. Standard OTC hydrocortisone labeling says not to use it for external feminine itching if you have a vaginal discharge, and to stop and see a doctor if symptoms last more than 7 days, or clear up and come back within a few days. Full warnings are listed below.","opinionAlerts":"0.25% is a lower strength than the 1% hydrocortisone in most drugstore anti-itch creams. Clinical figures are brand-reported."}'::jsonb, 'Alubri says its products are co-developed by co-founder Dr. Nicole Kerner, a board-certified, menopause-certified OB-GYN.,
  ('p-alubri-vulva-balm', 'Alubri Vulva Balm', 'Alubri', 'intimate-care', 'physical', 'A non-greasy balm to instantly soothe, hydrate, and nourish the vulva. It combines hyaluronic acid (sodium hyaluronate), a peptide, and dragon fruit extract with Alubri''s Activated Oil Complex, oat, green tea, and Tasmanian pepperberry extracts to support moisture retention and the skin barrier. Hormone-free, fragrance-free, and hypoallergenic.', '$24.99 (50 g)', '/products/alubri/vulva-balm.png', 'https://alubri.com/products/vulva-balm', '["discomfort","comfort","menopause","hormone-free","external-only"]'::jsonb, '["vaginal-health"]'::jsonb, '["alubri.com","Amazon","Walmart","Mayo Clinic Store"]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Sold as a cosmetic / personal-care product; not an FDA-cleared medical device or drug.","materials":"50 g (1.7 oz) jar. Ingredients: aqua (water), dimethicone, isododecane, caprylic/capric triglyceride, ozokerite, propanediol, sorbitan oleate, dimethicone crosspolymer, ceresin, hydrolyzed Rosa canina (rosehip) fruit oil, hydrolyzed Cocos nucifera (coconut) oil, sodium hyaluronate, palmitoyl hexapeptide-52, Hylocereus undatus (dragon fruit) fruit extract, Tasmannia lanceolata (Tasmanian pepperberry) fruit extract, Avena sativa (oat) kernel extract, Camellia sinensis (green tea) leaf extract, Passiflora incarnata flower extract, tocopherol, alpha-glucan oligosaccharide, tocopheryl acetate, Lactobacillus ferment lysate, biosaccharide gum-4, adenosine, ethylhexylglycerin, phenoxyethanol, sodium chloride, benzyl alcohol, potassium sorbate, benzoic acid.","recalls":"No recalls found.","sideEffects":"For external vulvar use. Discontinue and see a doctor if you notice irritation or an allergic reaction. Full warnings are listed below.","opinionAlerts":"Brand states products are \"not intended to diagnose, treat, cure, or prevent any disease.\" Clinical figures are brand-reported."}'::jsonb, 'Alubri says its products are co-developed by co-founder Dr. Nicole Kerner, a board-certified, menopause-certified OB-GYN, and that the balm is gynecologist- and dermatologist-tested.,
  ('p-alubri-vaginal-wellness-kit', 'Alubri Vaginal Wellness Kit', 'Alubri', 'intimate-care', 'physical', 'A trial-size, 2-week starter set pairing Alubri''s two core moisturizers in a zip pouch: the Vaginal Moisturizing Gel for internal dryness (30 mL, with 4 single-use applicators) and the Intimate Serum for external vulvar hydration (28 mL). A lower-cost way to try both before buying full sizes.', '$19.99 (2-week supply)', '/products/alubri/vaginal-wellness-kit.webp', 'https://alubri.com/products/vaginal-wellness-kit-bag-version', '["discomfort","comfort","menopause","hormone-free","travel-friendly"]'::jsonb, '["vaginal-health"]'::jsonb, '["alubri.com","Amazon","Walmart"]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Both products are sold as cosmetic / personal-care products; not FDA-cleared medical devices or drugs.","materials":"Zip pouch containing 1 × 30 mL (1.0 fl oz) Vaginal Moisturizing Gel, 1 × 28 mL (0.9 fl oz) Intimate Serum, and 4 single-use applicators. Full ingredient lists are on the Alubri Vaginal Moisturizing Gel and Alubri Intimate Serum entries. Hormone-free and fragrance-free.","recalls":"No recalls found.","sideEffects":"Discontinue and see a doctor if you notice irritation, burning, or an allergic reaction. Full warnings are listed below.","opinionAlerts":"Clinical figures for each product are brand-reported (see the full-size Gel and Serum entries)."}'::jsonb, 'Same two formulas as Alubri''s full-size Vaginal Moisturizing Gel and Intimate Serum, co-developed by co-founder Dr. Nicole Kerner, a board-certified, menopause-certified OB-GYN, per the brand.
on conflict (id) do update set
    name = excluded.name,
    brand = excluded.brand,
    category = excluded.category,
    product_type = excluded.product_type,
    summary = excluded.summary,
    price = excluded.price,
    image = excluded.image,
    url = excluded.url,
    tags = excluded.tags,
    health_functions = excluded.health_functions,
    where_to_buy = excluded.where_to_buy,
    where_to_buy_in_stock = excluded.where_to_buy_in_stock,
    safety = excluded.safety,
    doctor_opinion = excluded.doctor_opinion,
    community_review = excluded.community_review,
    effectiveness = excluded.effectiveness,
    clinician_opinion_source = excluded.clinician_opinion_source,
    clinician_attribution = excluded.clinician_attribution,
    source = excluded.source,
    internal = excluded.internal,
    requires_prescription = excluded.requires_prescription,
    user_rating = excluded.user_rating,
    is_active = excluded.is_active,
    extra = excluded.extra;
