-- gina.health products, added on request 2026-08-25 after being flagged in
-- the tracker_brands batches as an uncertain brand-identity match. Confirmed
-- here to be the intended brand and added directly. Both URLs and images
-- verified live via curl (200) just now. A third product linked from their
-- own collection page ("Sleep") 404s even on their own site — left out
-- rather than guessed at.
-- ON CONFLICT DO NOTHING — never touches an existing row even if re-run.

insert into public.product_catalog (id, name, brand, category, product_type, summary, price, image, url, tags, health_functions, where_to_buy, where_to_buy_in_stock, safety, doctor_opinion, community_review, effectiveness, clinician_opinion_source, clinician_attribution, source, internal, requires_prescription, user_rating, is_active, extra)
values
  ('p-gina-power-protein', 'POWER Protein Builder + Hormone Regulation', 'gina', 'supplement', 'physical', 'A daily amino-acid protein powder the brand states is formulated with a proprietary "GG Delta Gold" compound to support hormone regulation alongside protein intake.', '$72', 'https://www.gina.health/cdn/shop/files/POWER_afa5b76a-ff60-41c3-af13-3eaf5f6b0fb4.jpg?v=1740581520', 'https://www.gina.health/products/power-protein-builder-hormone-regulation', '["protein","hormone-balance","amino-acids"]'::jsonb, '["hormone-balance"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Dietary supplement; not evaluated by the FDA.","materials":"Amino-acid protein blend with a proprietary compound the brand calls GG Delta Gold — see brand site for full ingredient list.","recalls":"No recalls found.","sideEffects":"Consult a clinician before use if you take hormonal medication (birth control, HRT, thyroid medication) — a supplement marketed specifically for hormone regulation is worth a conversation with your provider first."}'::jsonb, 'Amino-acid protein supplementation itself is well-established and safe for most people. The specific claim that this formula is "clinically proven to regulate your hormones" is a strong, specific medical claim from an unregulated dietary supplement — no independent study of this exact product or its proprietary compound was found, so that claim should be treated as unverified brand marketing, not established evidence.', null, 'No independent, peer-reviewed study of this product or its "GG Delta Gold" compound was found. Protein supplementation generally has real evidence for muscle/recovery support; the hormone-regulation claim specifically is the brand''s own and not independently substantiated here.', 'brand', 'Sourced from gina''s own site; not independently verified here.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true,"stockNote":"Listed as sold out on the brand''s own site as of 2026-08-25 — verify current stock before promoting."}'::jsonb),
  ('p-gina-mineralize', 'MINERALIZE — Shilajit PLUS', 'gina', 'supplement', 'physical', 'A mineral supplement combining shilajit and deep-sea ocean plasma, marketed for hydration, energy, and mineral repletion.', '$65', 'https://www.gina.health/cdn/shop/files/MINERALIZED.jpg?v=1740431199', 'https://www.gina.health/products/mineral-shilajit-ocean-plasma', '["shilajit","minerals","energy"]'::jsonb, '["energy-support"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Dietary supplement; not evaluated by the FDA.","materials":"Shilajit and ocean plasma mineral blend — see brand site for full ingredient list.","recalls":"No recalls found.","sideEffects":"Unpurified shilajit products have a well-documented real-world risk of heavy-metal contamination (lead, arsenic) if not properly processed and third-party tested — worth confirming the brand''s purity/testing certification before use, and checking with a clinician if pregnant, nursing, or on medication."}'::jsonb, 'Shilajit is a real, traditionally-used mineral-rich substance with growing modern supplement use; its main real safety consideration as a category is heavy-metal contamination risk in poorly purified products, not specific to this brand but worth knowing. No independent study of this specific product''s purity or effectiveness was found.', null, 'Shilajit has modest independent supplement-category evidence for fatigue/energy in small trials; this product''s specific blend with ocean plasma and any brand-specific effectiveness claim were not independently verified here.', 'brand', 'Sourced from gina''s own site; not independently verified here.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true,"stockNote":"Listed as sold out on the brand''s own site as of 2026-08-25 — verify current stock before promoting."}'::jsonb)
on conflict (id) do nothing;
