-- Second batch of real products from Aditi's partnership tracker (2026-08-25).
-- Every URL/image below independently re-verified live via curl (200),
-- separate from the browse tool the researching agents used (confirmed
-- cross-contamination between concurrent forks sharing one browser session
-- today — nothing here was trusted from that path alone).
--
-- Deliberately NOT included from this round, for real reasons rather than
-- laziness:
--   - Connect PFF: connectpff.com is a pre-launch "coming soon" placeholder,
--     no live storefront exists yet.
--   - gina: found gina.health, but it's a general (not women's-health-
--     specific) hormone-supplement brand and there's real risk it's not the
--     same "gina" on the tracker — flagged for Aditi to confirm rather than
--     guessed.
--   - Tabu: tabu.co is real but reads as a low-trust supplement funnel —
--     generic unverifiable "Dr./Prof." testimonials, an inflated crossed-out
--     "was $164" against a "$39/mo" price, and unusually confident claims
--     about safety alongside endometriosis medication/HRT/birth control for
--     an unregulated product. Doesn't clear this catalog's bar; flagged for
--     Aditi to decide rather than added as a clean recommendation.
--   - YON E Health, BUNI, VIO2 (prior batch), Clair Health (prior batch):
--     no real, operating, findable company confirmed.
-- ON CONFLICT DO NOTHING — never touches an existing row even if re-run.

insert into public.product_catalog (id, name, brand, category, product_type, summary, price, image, url, tags, health_functions, where_to_buy, where_to_buy_in_stock, safety, doctor_opinion, community_review, effectiveness, clinician_opinion_source, clinician_attribution, source, internal, requires_prescription, user_rating, is_active, extra)
values
  ('p-alubri-vaginal-moisturizing-gel', 'Vaginal Moisturizing Gel', 'Alubri', 'intimate-care', 'physical', 'A clinically studied internal vaginal moisturizer from Alubri (co-founded by a board-certified OB/GYN) that the brand states provides up to 72 hours of hydration per application and is formulated to support a balanced vaginal microbiome.', '$29.99', 'https://cdn.shopify.com/s/files/1/0776/1192/5754/files/860013712334_1_94e56251-a89c-49e7-921a-6470d8616f62.jpg?v=1771002384', 'https://alubri.com/products/vaginal-moisturizing-gel', '["vaginal-dryness","moisturizer","microbiome"]'::jsonb, '["vaginal-health"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Cosmetic/wellness product; not an FDA-evaluated drug.","materials":"See brand site for full ingredient list.","recalls":"No recalls found.","sideEffects":"Persistent dryness, pain with sex, or irritation that doesn''t improve should be evaluated by a clinician rather than managed with a moisturizer alone."}'::jsonb, 'Internal vaginal moisturizers work by adhering to vaginal tissue and releasing water over time, distinct from a lubricant used only during sex — a reasonable option for chronic dryness from menopause, breastfeeding, certain medications, or other causes. Alubri is co-founded by a board-certified OB/GYN and states the formula increases protective Lactobacillus while reducing Gardnerella vaginalis; that specific microbiome claim is the brand''s own and wasn''t independently verified here.', null, 'Alubri describes the gel as "clinically proven" for up to 72 hours of hydration, but no independent, peer-reviewed study of this specific product was found — that claim is the brand''s own. Vaginal moisturizers as a category do have general clinical support for relieving dryness-related discomfort.', 'brand', 'Sourced from Alubri''s own site; not independently verified here.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true}'::jsonb),
  ('p-alubri-intimate-serum', 'Intimate Serum', 'Alubri', 'intimate-care', 'physical', 'A water-based intimate skin serum from Alubri intended for daily use to improve external intimate-area hydration and softness over time.', '$24.99', 'https://cdn.shopify.com/s/files/1/0776/1192/5754/files/860013712303_1.jpg?v=1771002315', 'https://alubri.com/products/intimate-serum', '["intimate-care","hydration"]'::jsonb, '["vaginal-health"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Cosmetic product; not an FDA-evaluated drug.","materials":"See brand site for full ingredient list.","recalls":"No recalls found.","sideEffects":"A patch test is reasonable before regular use; anyone with active irritation or suspected infection should see a clinician rather than self-treat."}'::jsonb, 'Positioned as an external, daily-use serum for vulvar skin rather than an internal vaginal product — lower-risk than an internal product.', null, 'No independent clinical study of this specific product was found; the brand''s hydration/softness claims are consistent with how water-based humectant serums generally work, but that''s category-level, not product-specific evidence.', 'brand', 'Sourced from Alubri''s own site; not independently verified here.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true}'::jsonb),
  ('p-hygiene-hero-v-fresh-go-atomizer', 'V Fresh & Go The Petite Atomizer', 'Hygiene Hero', 'intimate-care', 'physical', 'A small, refillable travel spray bottle from Hygiene Hero sized to carry the brand''s V Fresh & Go intimate cleansing mist for on-the-go use.', '$10.00', 'https://cdn.shopify.com/s/files/1/0357/0470/1060/files/openrefillminibottlelayflatonwhitemarble.jpg?v=1754895365', 'https://hygiene-hero.com/products/v-fresh-go-the-petite-atomizer', '["intimate-care","travel"]'::jsonb, '["vaginal-health"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Accessory item; not a regulated product itself.","materials":"See brand site.","recalls":"No recalls found.","sideEffects":"Fragranced sprays near vulvar skin can irritate sensitive users — the mist''s own ingredient list matters more than the bottle. Unusual odor, discharge, or discomfort warrants a clinician visit, not a cosmetic product."}'::jsonb, 'An accessory for carrying an external intimate mist, not a treatment — external mists/washes are generally lower-risk than internal products.', null, 'An accessory, not an active product — its function is holding/dispensing the Cleansing Mist sold separately. No independent testing of that mist formula was reviewed here.', 'brand', 'Sourced from Hygiene Hero''s own site; not independently verified here.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true}'::jsonb),
  ('p-hygiene-hero-perfect-pause-kit', 'Perfect Pause Private Kit', 'Hygiene Hero', 'menopause', 'physical', 'A vulvar-care bundle (cleansing bar plus "VV Oil") from Hygiene Hero marketed specifically for menopause-related changes in vulvar skin comfort.', '$77.90', 'https://cdn.shopify.com/s/files/1/0357/0470/1060/files/IMG_0085PPPrivateKitComplete_closeup.jpg?v=1694446274', 'https://hygiene-hero.com/products/perfect-pause-kit', '["menopause","vulvar-care","intimate-care"]'::jsonb, '["menopause-support","vaginal-health"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Cosmetic products; not FDA-evaluated drugs.","materials":"Cleansing bar and oil blend — see brand site for full ingredients.","recalls":"No recalls found.","sideEffects":"This is cosmetic, not a treatment for genitourinary syndrome of menopause (GSM); significant symptoms are worth raising with a gynecologist, who may discuss a prescription option."}'::jsonb, 'Declining estrogen in menopause can reduce vulvar tissue elasticity/moisture, a legitimate rationale for a dedicated comfort line — but this is cosmetic, not a clinical treatment.', null, 'No independent clinical study of this specific kit was found; gentle vulvar skincare is a reasonable general comfort measure during menopause, but that''s category-level, not product-specific evidence.', 'brand', 'Sourced from Hygiene Hero''s own site; not independently verified here.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true}'::jsonb),
  ('p-hello-period-high-achiever-underwear', 'High Achiever Seamless High Waist Period Underwear', 'Hello Period', 'period-underwear', 'physical', 'Seamless, high-waist period underwear with a leakproof sealed gusset, made without added PFAS and OEKO-TEX Standard 100 certified.', '$45.99', 'https://cdn.shopify.com/s/files/1/0280/3413/8205/files/High_waist_period_underwear.png?v=1782969198', 'https://helloperiod.com/products/high-achiever-hello-undies-high-waist', '["period-underwear","leakproof","pfas-free"]'::jsonb, '["leak-protection"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Textile product; not FDA-regulated.","materials":"See brand site; OEKO-TEX Standard 100 certified.","recalls":"No recalls found.","sideEffects":"None specific; standard textile-sensitivity caveats apply."}'::jsonb, 'Works as a physical absorbency/leak barrier for light-to-moderate flow or as backup on heavier days; doesn''t treat any underlying condition. The "no added PFAS" claim addresses a real documented concern in this category (independent testing has found PFAS in some period underwear); OEKO-TEX Standard 100 is a real independently-administered textile standard, though "no added PFAS" itself is the brand''s formulation claim, not confirmed third-party PFAS testing of the finished product.', null, 'No independent lab testing of this product''s absorbency or PFAS content was reviewed here. Reusable period underwear as a category has real evidence of leak protection comparable to disposable pads for appropriate flow levels.', 'brand', 'Sourced from Hello Period''s own site; not independently verified here.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true}'::jsonb),
  ('p-hello-period-hottie-heat-patches', 'Hello Hottie Air Activated Heat Patches (3-Pack)', 'Hello Period', 'cramp-relief', 'physical', 'Adhesive, air-activated heat patches that stick to clothing over the lower abdomen for up to 8 hours of warmth to help with period cramps.', '$14.99', 'https://cdn.shopify.com/s/files/1/0280/3413/8205/files/Hello_Hottie_shots_3.png?v=1785969731', 'https://helloperiod.com/products/hello-hottie', '["heat-therapy","cramps"]'::jsonb, '["cramp-relief"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"OTC heat-therapy product.","materials":"Air-activated adhesive heat patch.","recalls":"No recalls found.","sideEffects":"Avoid applying directly to bare skin per instructions to prevent burns; severe, sudden, or unusual cramping warrants a clinician visit."}'::jsonb, 'Heat therapy is a well-established, low-risk OTC approach to menstrual cramps, with real clinical evidence comparable in some studies to OTC pain relievers for mild-to-moderate cramps.', null, 'No independent study of this specific product was found, but topical heat therapy for menstrual cramps broadly has real published clinical support — a well-evidenced category even without product-specific data.', 'brand', 'Sourced from Hello Period''s own site; not independently verified here.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true}'::jsonb),
  ('p-livlabs-pippa-fit-kit', 'Pippa Resistance Spring Fit Kit', 'Liv Labs', 'pelvic-floor', 'physical', 'A wearable spring-form pelvic floor trainer worn passively during exercise or daily movement, developed over 7 years with female engineers, athletes, and clinical experts.', '$149', 'https://cdn.shopify.com/s/files/1/0771/1087/0265/files/PippaFitKit_fa102407-c5cf-447f-8220-b68fd8c917e3.png?v=1764361668', 'https://livlabsfitness.com/products/pippa-fit-kit', '["pelvic-floor","postpartum","wearable"]'::jsonb, '["pelvic-floor-strength","postpartum-recovery"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Wellness/fitness accessory; not a medical device.","materials":"Body-safe, BPA-free silicone (brand-stated).","recalls":"No recalls found.","sideEffects":"Not a treatment for diagnosed pelvic floor dysfunction — anyone with significant prolapse, incontinence, or pain should see a pelvic floor PT rather than self-treat with any wearable device."}'::jsonb, 'Pippa is a spring-form wearable that provides continual light resistance against the pelvic floor, intended to improve neuromuscular activation rather than requiring active kegel repetitions. The brand states it is recommended by pelvic health physical therapists and safe for daily use, including during pregnancy and menstruation.', 'On-site reviews (4.8/5, 11 reviews, not independently verified elsewhere) describe comfort and ease of use; one reviewer specifically noted it didn''t help her stress incontinence as much as hoped, so results are mixed by individual, as with any pelvic floor product.', 'The brand states its own clinical study abstract has been published and holds a U.S. patent for the resistance-spring mechanism; this is the brand''s own study, not independently reviewed here. Pelvic floor muscle training generally (kegels, biofeedback devices) has real independent clinical evidence for stress incontinence and postpartum recovery — this product''s specific passive-wear mechanism is a newer approach without independent third-party trials found.', 'brand', 'Sourced from Liv Labs'' own site; not independently verified here.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true}'::jsonb)
on conflict (id) do nothing;
