-- Adds Winx Health's remaining real standalone products, and fixes the
-- existing product's url (was the bare homepage; now the actual product page).
-- ON CONFLICT DO NOTHING on the inserts: never updates or touches any
-- existing row, even if this is accidentally run twice.

update product_catalog
set url = 'https://hellowinx.com/products/uti-tests'
where id = 'p-winx-uti-test-treat';

insert into public.product_catalog (id, name, brand, category, product_type, summary, price, image, url, tags, health_functions, where_to_buy, where_to_buy_in_stock, safety, doctor_opinion, community_review, effectiveness, clinician_opinion_source, clinician_attribution, source, internal, requires_prescription, user_rating, is_active, extra)
values
  ('p-winx-vaginal-health-test-treat', 'Winx Health Vaginal Health Test + Treat', 'Winx Health', 'diagnostics', 'physical', 'An at-home vaginal pH test to help tell a yeast infection, BV, or something else apart, with same-day prescription treatment available via Winx''s own telehealth service if needed.', '$15', 'https://cdn.shopify.com/s/files/1/0077/8761/0171/files/Vaginal_Health_Test_Treat_Graphic.png?v=1771347513', 'https://hellowinx.com/products/vaginal-ph-test-for-yeast-infections', '["privacy","safety-concern"]'::jsonb, '["vaginal-health","telehealth"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Consumer diagnostic test; any prescription treatment is issued by a licensed telehealth provider, not the test itself.","materials":"See product packaging for full test component list.","recalls":"No recalls found.","sideEffects":"None specific to the test itself; any treatment side effects depend on the medication a provider prescribes.","opinionAlerts":"Marketed by Winx Health as its own product; verify current claims and availability directly at hellowinx.com."}'::jsonb, 'Winx Health positions this as a way to tell yeast infection, BV, or other causes apart at home before deciding whether treatment is needed.', null, 'Combines an at-home pH test with telehealth access to prescription treatment when appropriate; no independent clinical study of the product was found.', 'brand', 'Sourced from Winx Health''s own site marketing claims, not independent clinical literature.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true}'::jsonb),
  ('p-winx-pregnancy-tests', 'Winx Health Early Pregnancy Tests', 'Winx Health', 'diagnostics', 'physical', 'Early pregnancy tests from Winx Health (formerly Stix), the brand states are over 99% accurate, with discreet packaging and delivery.', '$13', 'https://cdn.shopify.com/s/files/1/0077/8761/0171/files/Early_Pregnancy_Tests.png?v=1775185073', 'https://hellowinx.com/products/pregnancy-tests', '["privacy"]'::jsonb, '["fertility"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Over-the-counter home pregnancy test.","materials":"See product packaging.","recalls":"No recalls found.","sideEffects":"None.","opinionAlerts":"Accuracy claim (\"over 99% accurate\") is the brand''s own; not independently verified here."}'::jsonb, 'A standard at-home pregnancy test; Winx Health emphasizes discreet packaging and privacy.', null, 'Positioned as an accurate, private at-home pregnancy test; no independent clinical study of the product was found.', 'brand', 'Sourced from Winx Health''s own site marketing claims, not independent clinical literature.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true}'::jsonb),
  ('p-winx-uti-pain-relief', 'Winx Health UTI Fast-Acting Pain Relief', 'Winx Health', 'supplement', 'physical', 'An over-the-counter supplement from Winx Health marketed for fast-acting relief of UTI-related discomfort.', '$10.50', 'https://cdn.shopify.com/s/files/1/0077/8761/0171/files/01WinxUTIPainReliefHero.png?v=1771347535', 'https://hellowinx.com/products/uti-fast-acting-pain-relief', '["uti"]'::jsonb, '["uti-prevention"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Dietary supplement; not evaluated by the FDA.","materials":"See product packaging for full ingredient list.","recalls":"No recalls found.","sideEffects":"Consult a clinician before use if pregnant, nursing, or taking medications; UTI pain relief products can mask symptoms of a worsening infection.","opinionAlerts":"No clinical-study claims found on the brand site."}'::jsonb, 'Positioned by the brand for short-term relief of UTI discomfort, not as a substitute for diagnosis or treatment.', null, 'Positioned as fast-acting symptom relief; no independent clinical study of the product was found.', 'brand', 'Sourced from Winx Health''s own site marketing claims, not independent clinical literature.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true}'::jsonb),
  ('p-winx-vaginal-probiotic', 'Winx Health Vaginal Health Probiotic', 'Winx Health', 'supplement', 'physical', 'A daily probiotic supplement the brand describes as supporting vaginal health with "good bacteria" that can help crowd out bacteria and yeast linked to BV and yeast infections.', '$28', 'https://cdn.shopify.com/s/files/1/0077/8761/0171/files/01_Winx_probiotic_Hero.png?v=1771347498', 'https://hellowinx.com/products/vaginal-health-probiotic', '["comfort"]'::jsonb, '["vaginal-health"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Dietary supplement; not evaluated by the FDA.","materials":"See product packaging for full ingredient list.","recalls":"No recalls found.","sideEffects":"Consult a clinician before use if pregnant, nursing, or taking medications.","opinionAlerts":"No clinical-study claims found on the brand site."}'::jsonb, 'Positioned as daily maintenance support for vaginal flora balance, not a treatment for an active infection.', null, 'Positioned as a daily preventive supplement; no independent clinical study of the product was found.', 'brand', 'Sourced from Winx Health''s own site marketing claims, not independent clinical literature.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true}'::jsonb),
  ('p-winx-uti-daily-defense', 'Winx Health Urinary Daily Defense', 'Winx Health', 'supplement', 'physical', 'A daily supplement the brand states was designed with urologists, using science-backed natural ingredients intended to help protect against UTIs before they start.', '$28', 'https://cdn.shopify.com/s/files/1/0077/8761/0171/files/01WinxDailyDefenseHero.png?v=1771339808', 'https://hellowinx.com/products/uti-daily-protection-supplement', '["uti"]'::jsonb, '["uti-prevention"]'::jsonb, '[]'::jsonb, '{}'::jsonb, '{"fdaStatus":"Dietary supplement; not evaluated by the FDA.","materials":"See product packaging for full ingredient list.","recalls":"No recalls found.","sideEffects":"Consult a clinician before use if pregnant, nursing, or taking medications.","opinionAlerts":"The \"designed with urologists\" claim is the brand''s own; not independently verified here."}'::jsonb, 'Positioned as a daily preventive supplement for recurrent UTI risk, not a treatment for an active infection.', null, 'Positioned as a daily preventive supplement; no independent clinical study of the product was found.', 'brand', 'Sourced from Winx Health''s own site marketing claims, not independent clinical literature.', 'curated', false, false, null, true, '{"integrations":[],"badges":[],"isEmergingBrand":true}'::jsonb)
on conflict (id) do nothing;
